Raw_Data: 
  Train: data/raw/train.csv
  Test: data/raw/test.csv

Cat_treatment:
  Drug: [Placebo, D-penicillamine]
  Sex: [F, M]
  Ascites: [Y, N]
  Hepatomegaly: [Y, N]
  Spiders: [Y, N]
  Edema: [Y, N, S]
  Status: [C, CL, D]

Format_change: 
  N_Days: N_years
  Age: Age_in_years

Num_treatment:
  Age_in_years: [16, 100]
  N_years: Age_in_years
  Bilirubin: [0.1, 50]
  Cholesterol: [60, 1500]
  Albumin: [1, 6.5]
  Copper: [10, 800]
  Alk_Phos: [20, 6000] 
  SGOT: [5, 10000]
  Tryglicerides: [20, 5000]
  Platelets: [10, 1000]
  Prothrombin: [8, 70]

Columns:
  Num_cols: [Bilirubin, Cholesterol, Albumin, Copper, Alk_Phos, SGOT, Tryglicerides, Platelets, Prothrombin]
  Cat_cols: [Drug, Sex, Ascites, Hepatomegaly, Spiders, Edema, Status]

Processed_Data:
  Dir_path: data/processed
  Train_file: train.csv
  Test_file: test.csv

Splitting:
  Validation_size: 0.2
  Seed: 16
  Dir_path: data/interim
  Train_file: train_set.csv
  Validation_file: validation_set.csv
