Input_Data: data/interim/train_set.csv

Columns:
  Exclude: id
  Target: Status

Hyperparameters:
  iterations: 377
  depth: 3
  learning_rate: 0.210751086669541
  border_count: 345
  cat_features: [Drug, Sex, Ascites, Hepatomegaly, Spiders, Edema]
  loss_function: MultiClass
  random_state: 25
  allow_writing_files: False

Model_save:
  Root_dir: models
  Model_name: model.joblib  